[credentials]
intellisearch_job_id = 367189284162575
Keyword_extraction_job_id=1062717292802339
server_hostname= "https://adb-8566293101107632.12.azuredatabricks.net"
http_path ="/sql/1.0/warehouses/908d51cba3348877"
access_token ="dapid06c02dff6c61b4b4df05256997ae561-3"
workspace_url = "https://adb-8566293101107632.12.azuredatabricks.net"
AZURE_CONNECTION_STRING = "DefaultEndpointsProtocol=https;AccountName=adlsusdldev02;AccountKey=EHYAgBny50jsQr4uRtspr3UnFCXyg8wbAInIsZEjNfFM+NEmU3rY2eQ9gfBNgS5Of/OdHfk2cAQo+AStwu3MSA==;EndpointSuffix=core.windows.net"
CONTAINER_NAME= "intellitag"